language: python

python:
    - "2.7"

sudo: required

virtualenv:
  system_site_packages: true

before_install:
    - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
    - sudo apt-get install -qq python-scipy python-nose python-nibabel python-sklearn python-networkx python-nipype
    - sudo apt-get install -qq python-pip
    - pip install "nilearn>=0.1.3"
    - pip install coverage coveralls

install:
    - python setup.py install

script:
    - make clean
    - make test-code

after_success:
    - coveralls
