# AUTO-GENERATED by tools/checkspecs.py
# DO NOT EDIT
from nose.tools import assert_equal
from procasl.preprocessing import Rescale


def test_Rescale_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(copyfile=True,
    mandatory=True,
    ),
    label_efficiency=dict(usedefault=True,
    ),
    ss_tr=dict(mandatory=True,
    ),
    t1_blood=dict(usedefault=True,
    ),
    t_i_1=dict(mandatory=True,
    ),
    t_i_2=dict(mandatory=True,
    ),
    )
    inputs = Rescale.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_Rescale_outputs():
    output_map = dict(rescaled_file=dict(),
    )
    outputs = Rescale.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
