# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nose.tools import assert_equal
from procasl.quantification import QuantifyCBF


def test_QuantifyCBF_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    m0_file=dict(copyfile=True,
    mandatory=True,
    ),
    perfusion_file=dict(copyfile=True,
    mandatory=True,
    ),
    t1_gm=dict(usedefault=True,
    ),
    tr=dict(mandatory=True,
    usedefault=True,
    ),
    )
    inputs = QuantifyCBF.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_QuantifyCBF_outputs():
    output_map = dict(cbf_file=dict(),
    )
    outputs = QuantifyCBF.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
